import { useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, View } from 'react-native';
import AppButton from '../components/AppButton';
import { sendSmsCode, verifySmsCode } from '../services/authService';
import { getPhoneAuthVerifier } from '../services/phoneAuthBridge';
import { colors, radii, spacing, typography } from '../theme/theme';
export default function PhoneAuthScreen({ navigation, mode = 'login' }) {
  const [phone, setPhone] = useState('+52 '); const [code, setCode] = useState(''); const [verificationId, setVerificationId] = useState(''); const [loading, setLoading] = useState(false); const register = mode === 'register';
  async function sendCode() { if (phone.replace(/\D/g, '').length < 12) return Alert.alert('Número incompleto', 'Ingresa tu número con lada y código de país.'); const verifier = getPhoneAuthVerifier(); if (!verifier) return Alert.alert('Configura Firebase Phone Auth', 'Registra el verificador nativo del development build. Mientras tanto puedes explorar la demo navegable.'); try { setLoading(true); setVerificationId(await sendSmsCode(phone.replace(/\s/g, ''), verifier)); Alert.alert('Código enviado', 'Revisa tus mensajes SMS e ingresa el código de 6 dígitos.'); } catch (error) { Alert.alert('No se pudo enviar el SMS', error.message); } finally { setLoading(false); } }
  async function verify() { if (code.length < 6) return Alert.alert('Código incompleto', 'Ingresa el código de 6 dígitos enviado por SMS.'); try { setLoading(true); await verifySmsCode(verificationId, code); navigation.replace('Dashboard'); } catch (error) { Alert.alert('No se pudo iniciar sesión', error.message); } finally { setLoading(false); } }
  return <View style={styles.screen}><View><Text style={styles.eyebrow}>MI JUZGADO VIRTUAL</Text><Text style={styles.title}>{register ? 'Crea tu cuenta' : 'Inicia sesión'}</Text><Text style={styles.copy}>{register ? 'Regístrate con tu número celular. Te enviaremos un código de verificación por SMS.' : 'Ingresa tu celular para revalidar tu acceso de forma segura por SMS.'}</Text></View><View style={styles.form}><Text style={styles.label}>Número de celular</Text><TextInput value={phone} onChangeText={setPhone} keyboardType="phone-pad" style={styles.input} placeholder="+52 55 1234 5678" />{!!verificationId && <><Text style={styles.label}>Código SMS</Text><TextInput value={code} onChangeText={setCode} keyboardType="number-pad" maxLength={6} style={styles.input} placeholder="000000" /></>}<AppButton loading={loading} title={verificationId ? 'Verificar código' : 'Enviar código SMS'} onPress={verificationId ? verify : sendCode} /><AppButton variant="secondary" title="Entrar a demo navegable" onPress={() => navigation.replace('Dashboard')} /></View><Text style={styles.bottom}>{register ? '¿Ya tienes cuenta?' : '¿Aún no tienes cuenta?'} <Text onPress={() => navigation.replace(register ? 'Login' : 'Register')} style={styles.link}>{register ? 'Iniciar sesión' : 'Registrarme'}</Text></Text></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.white, padding: spacing.xl, justifyContent: 'space-between' }, eyebrow: { ...typography.small, color: colors.teal, fontWeight: '800', marginTop: spacing.xxxl }, title: { ...typography.h1, color: colors.ink, marginTop: spacing.sm }, copy: { ...typography.body, color: colors.muted, marginTop: spacing.md }, form: { gap: spacing.md }, label: { ...typography.small, color: colors.ink, fontWeight: '700' }, input: { minHeight: 52, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, backgroundColor: colors.surface, paddingHorizontal: spacing.lg, ...typography.body, color: colors.ink }, bottom: { ...typography.body, textAlign: 'center', color: colors.text, paddingBottom: spacing.xl }, link: { color: colors.teal, fontWeight: '800' } });
